site_name: PDOPT Documentation

nav:
  - Home: index.md
  - About: about.md
  - Tutorial: tutorial.md
  - API Reference:
    - pdopt.data : data.md
    - pdopt.exploration : exploration.md
    - pdopt.optimization : optimization.md
    - pdopt.tools : tools.md

theme: readthedocs

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            heading_level: 1
            parameter_headings: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: false
            show_root_members_full_path: true
            show_object_full_path: true
            docstring_section_style: table
            members_order: source
            show_source: false
            